#!/usr/bin/env ruby

# This script is a sort-of REPL for monitoring production data. It will
# periodically poll for production data and set off any alarms you define below.
# Useful for testing autoscaling policies.
#
# At any point of the running process, pressing ctrl + c will pause execution
# and drop you into a REPL where you can inspect the state of the program.
# Exiting the REPL will resume execution.
#
# To exit the program entirely, drop into the REPL and run "exit!".

require_relative '../config/environment/common'
require 'timecop'
include DynamoAutoscale

if ARGV[0]
  DynamoAutoscale.setup_from_config(ARGV[0], dry_run: true)
elsif ARGV[0].nil?
  STDERR.puts "Usage: script/monitor path/to/config.yml"

  exit 1
elsif ARGV[0] and !File.exists?(ARGV[0])
  STDERR.puts "Usage: script/monitor path/to/config.yml"
  STDERR.puts "Error: The path you specified is to a file that does not exist."

  exit 1
end

begin
  DynamoAutoscale.poller.run
rescue SignalException, Interrupt
  Ripl.start :binding => binding
  retry
rescue => e
  # If we error out, print the error and drop into a repl.
  logger.error "Exception occurred: #{e.class}:#{e.message}"
  Ripl.start :binding => binding
end
