#!/usr/bin/env ruby

require_relative '../config/environment/common'
require 'pp'
require 'timecop'
include DynamoAutoscale
extend  DynamoAutoscale

graph   = !!(ARGV.delete("--graph") or ARGV.delete("-g"))
ruleset = ARGV.shift
tables  = ARGV

if tables.empty? or ruleset.nil?
  STDERR.puts "Usage: script/test ruleset table_name [another_table_name ... ] [-g|--graph]"
  exit 1
end

filters                        = LocalActioner.faux_provisioning_filters
DynamoAutoscale.rules          = RuleSet.new(ruleset)
DynamoAutoscale.dispatcher     = Dispatcher.new
DynamoAutoscale.poller         = LocalDataPoll.new(tables: tables, filters: filters)
DynamoAutoscale.actioner_class = LocalActioner
DynamoAutoscale.actioner_opts  = { group_downscales: true, flush_after: 2.hours }

# Uncomment this and the below RubyProf lines if you want profiling information.
# RubyProf.start

begin
  DynamoAutoscale.poller.run do |table_name, time|
    Timecop.travel(time)
  end
rescue Interrupt
  Ripl.start binding: binding
end

# Uncomment these and the above RubyProf line if you want profiling information.
# printer = RubyProf::FlatPrinter.new(RubyProf.stop)
# printer.print(STDOUT, min_percent: 2)

# Uncomment this if you want to drop into a REPL at the end of the test.
# Ripl.start binding: binding

tables.each do |table_name|
  table = DynamoAutoscale.tables[table_name]

  table.report!

  if graph
    path = table.graph! open: true
    puts "Graph saved to #{path}"
  end
end
